### ISSUE TITLE
Doesn't work when posting

### ISSUE THREAD

**Issue by impactcolor** [uxweb/sweet-alert#93]
I've gotten the alerts to appear on a regular page but when I attempt to post and add it BEFORE my redirect it doesn't work.  Here's what I have:

```
public function store(Request $request)
{
// do some stuff
            Alert::message('Your order has been received', 'Thank you!');
            return redirect('dashboard-orders');
}
```
Here is my route:
`Route::post('/checkout', 'CheckoutController@store');`

I would expect the above to display an alert before the redirect but it does not.  I tested as a regular get and it works, when I try to post it doesn't work.  Any ideas what I'm doing wrong?

**Comment by debugdotdog** [comment]
So I believe I understand what you are asking. You want for someone to submit the form, the alert to show if the request was successful, and THEN redirect the user. 

The issue is that you are adding your `Alert::message` into your request and then redirecting the user to your `dashboard-orders` page, so it will show on the next page when you have access to the request data. To overcome this, you would need to make your form request using Ajax, return any other data you need along with the Sweetalert data, and then using something like this: 

```php
@if (Session::has('sweet_alert.alert'))
    <script>
        swal({
            text: "{!! Session::get('sweet_alert.text') !!}",
            title: "{!! Session::get('sweet_alert.title') !!}",
            icon: "{!! Session::get('sweet_alert.type') !!}",
        });
    </script>
@endif
```

There will be more you will need to do such as working out a way to refresh the component, I would suggest looking into baking some Vue components into your application. 

I hope this helps a bit, and if you need more help, just ask :)

**Comment by eleazarbr** [comment]
```
return redirect('dashboard-orders')->withSuccess('Your order has been received);
```

 I think if you do it this way, your alert will be displayed correctly on the next route
